### ISSUE TITLE
Logging abstraction using Adapter Pattern

### ISSUE THREAD

**Issue by jrosellr** [JoanRosell/SimpleCRUD#2]
# Description
To decouple the logging service from the actual framework I will apply the Adapter Pattern. The framework I will use for now is Serilog.

## Todos
- [ ] Create the Adapter interface and implement a SerilogLogger class
- [ ] Configure the Serilog logger
- [ ] Add a Console Appender and a Rolling File appender
