### ISSUE TITLE
Data Access Tier

### ISSUE THREAD

**Issue by jrosellr** [JoanRosell/SimpleCRUD#3]
# Description
In order to make this project database agnostic I plan to abstract the database interactions using the Repository Pattern together with the Unit Of Work pattern. These two patterns help abstract away the complexity of handling transactions in complex database contexts and they also reduce query duplication. In this app the UOW approach may be a little bit overkill, but I want to learn from this example anyway.

To further simplify the consumption of this Tier's services I will use the Facade Pattern to expose a simple interface to the services of the Business Tier.

## Todos
- [x] Configure EF
- [x] Implement the Generic Repository class / interface
- [x] Implement the StudentRepository class / interface (this is not really useful in this app, as we only use generic operations)
- [x] Implement the Unit Of Work class / interface to work with a StudentRepository
