### ISSUE TITLE
Business Tier

### ISSUE THREAD

**Issue by jrosellr** [JoanRosell/SimpleCRUD#4]
# Description
The Business Tier will be comprised of two layers:
1. Distributed Services Layer (DSL)
2. Business Logic (BL)

The DSL will implement a WCF service that will in turn call the BL services. This way we can decouple the Business Logic Layer from the services that consume it. We could change the WCF service to an ASP.NET WebService and everything should work just fine.

The BL will expose a simple interface through a StudentService will operate on a Student business entity. This entity should be able to calculate its Age. These Student business entities will be retrieved using the DA data persistence services.

## Todos
First I will implement the BL:
- [x] Implement the StudentService object
- [x] Implement the interactions between this layer and the DA facade

Then, I will work on how the DSL consumes the BL services:
- [x] Implement a Student WCF Service contract
- [x] Test the contract with the WinSite Layer
