### ISSUE TITLE
Add DI with Autofac

### ISSUE THREAD

**Issue by jrosellr** [JoanRosell/SimpleCRUD#9]
# Description
To further decouple the Services Layer from the Business Logic Layer Autofac should be used to inject the StudentService class into the StudentRemoteService.

## Todos
- [ ] Install Autofac and Autofac.wcf
- [ ] Create an InjectionConfig class and configure the container in the file Global.asax
- [ ] Update the *.svc file to add the Factory from Autofac
- [ ] Add the updated service name in the web.config file
